{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2748c13d-9d81-44ba-96fc-c23fadecb572",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-14 12:04:26.219 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:26.219 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:27.473 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.136 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\HP\\anaconda3\\envs\\Salary_Prediction\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-05-14 12:04:28.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.141 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.143 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.145 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.146 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.155 Session state does not function when running a script without `streamlit run`\n",
      "2026-05-14 12:04:28.156 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.170 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.183 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.184 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.216 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.220 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.236 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.243 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-14 12:04:28.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Page Configuration\n",
    "# --------------------------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"DevInsights Predictor\",\n",
    "    page_icon=\"💻\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Custom Transformer (Required for Loading Pipeline)\n",
    "# --------------------------------------------------\n",
    "class change_data_type(BaseEstimator, TransformerMixin):\n",
    "    def fit(self, X, y=None):\n",
    "        return self\n",
    "\n",
    "    def transform(self, X):\n",
    "        X = X.copy()\n",
    "        for col in X.columns:\n",
    "            if X[col].dtype in ['object']:\n",
    "                X[col] = X[col].astype('category')\n",
    "        return X\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Load Models\n",
    "# --------------------------------------------------\n",
    "@st.cache_resource\n",
    "def load_models():\n",
    "    models = joblib.load(\"full_system.pkl\")\n",
    "    return models[\"salary_model\"], models[\"satisfaction_model\"]\n",
    "\n",
    "\n",
    "try:\n",
    "    salary_model, satisfaction_model = load_models()\n",
    "except Exception as e:\n",
    "    st.error(f\"Error loading model: {e}\")\n",
    "    st.stop()\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Prediction Function\n",
    "# --------------------------------------------------\n",
    "def predict_job_satisfaction(\n",
    "    Age, EdLevel, Employment, WorkExp, LearnCodeChoose,\n",
    "    LearnCodeAI, YearsCode, DevType, OrgSize, ICorPM,\n",
    "    RemoteWork, PurchaseInfluence, AIThreat, NewRole,\n",
    "    ToolCountWork, ToolCountPersonal, Country, AIModelsChoice\n",
    "):\n",
    "    input_features = pd.DataFrame([{\n",
    "        \"Age\": Age,\n",
    "        \"EdLevel\": EdLevel,\n",
    "        \"Employment\": Employment,\n",
    "        \"WorkExp\": WorkExp,\n",
    "        \"LearnCodeChoose\": LearnCodeChoose,\n",
    "        \"LearnCodeAI\": LearnCodeAI,\n",
    "        \"YearsCode\": YearsCode,\n",
    "        \"DevType\": DevType,\n",
    "        \"OrgSize\": OrgSize,\n",
    "        \"ICorPM\": ICorPM,\n",
    "        \"RemoteWork\": RemoteWork,\n",
    "        \"PurchaseInfluence\": PurchaseInfluence,\n",
    "        \"AIThreat\": AIThreat,\n",
    "        \"NewRole\": NewRole,\n",
    "        \"ToolCountWork\": ToolCountWork,\n",
    "        \"ToolCountPersonal\": ToolCountPersonal,\n",
    "        \"Country\": Country,\n",
    "        \"AIModelsChoice\": AIModelsChoice\n",
    "    }])\n",
    "\n",
    "    # Predict Salary\n",
    "    salary = salary_model.predict(input_features)[0]\n",
    "\n",
    "    # Add predicted salary for satisfaction model\n",
    "    input_features[\"pred_salary\"] = salary\n",
    "\n",
    "    # Predict Satisfaction\n",
    "    satisfaction = satisfaction_model.predict(input_features)[0]\n",
    "\n",
    "    return salary, satisfaction\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Options\n",
    "# --------------------------------------------------\n",
    "age_options = [\n",
    "    '18-24 years old',\n",
    "    '25-34 years old',\n",
    "    '35-44 years old',\n",
    "    '45-54 years old',\n",
    "    '55-64 years old',\n",
    "    '65 years or older'\n",
    "]\n",
    "\n",
    "ed_level_options = [\n",
    "    'Bachelor’s degree',\n",
    "    'Master’s degree',\n",
    "    'Some college/university study without earning a degree',\n",
    "    'Secondary school',\n",
    "    'Professional degree',\n",
    "    'Associate degree',\n",
    "    'Primary/elementary school',\n",
    "    'Other doctoral degree',\n",
    "    'Something else'\n",
    "]\n",
    "\n",
    "employment_options = [\n",
    "    'Employed, full-time',\n",
    "    'Independent contractor, freelancer, or self-employed',\n",
    "    'Employed, part-time',\n",
    "    'Retired',\n",
    "    'Not employed, but looking for work',\n",
    "    'Student, full-time'\n",
    "]\n",
    "\n",
    "learn_code_options = [\n",
    "    'Other online resources',\n",
    "    'Books / Physical media',\n",
    "    'Online Courses or Certification',\n",
    "    'On the job training',\n",
    "    'School (i.e., University, College, etc)',\n",
    "    'Friend or family member'\n",
    "]\n",
    "\n",
    "learn_code_ai_options = [\n",
    "    'Online courses',\n",
    "    'Chatbots',\n",
    "    'Other',\n",
    "    'Videos',\n",
    "    'Interactive tutorials'\n",
    "]\n",
    "\n",
    "dev_type_options = [\n",
    "    'Developer, back-end',\n",
    "    'Developer, front-end',\n",
    "    'Developer, full-stack',\n",
    "    'Developer, desktop or enterprise applications',\n",
    "    'Developer, mobile',\n",
    "    'Data scientist or machine learning specialist',\n",
    "    'Engineer, data',\n",
    "    'DevOps specialist'\n",
    "]\n",
    "\n",
    "org_size_options = [\n",
    "    '20 to 99 employees',\n",
    "    '100 to 499 employees',\n",
    "    '10,000 or more employees',\n",
    "    '1,000 to 4,999 employees',\n",
    "    '2 to 9 employees',\n",
    "    '500 to 999 employees',\n",
    "    'Just me - I am a freelancer, sole proprietor, etc.'\n",
    "]\n",
    "\n",
    "ic_pm_options = [\n",
    "    'Individual contributor',\n",
    "    'Program manager'\n",
    "]\n",
    "\n",
    "remote_options = [\n",
    "    'Hybrid',\n",
    "    'Remote',\n",
    "    'In-person'\n",
    "]\n",
    "\n",
    "purchase_options = [\n",
    "    'I have some influence',\n",
    "    'I have little or no influence',\n",
    "    'I am a primary decision maker'\n",
    "]\n",
    "\n",
    "ai_threat_options = [\n",
    "    'I’m not at all concerned',\n",
    "    'I’m somewhat concerned',\n",
    "    'I’m very concerned'\n",
    "]\n",
    "\n",
    "new_role_options = [\n",
    "    'Not sure',\n",
    "    'Yes',\n",
    "    'No'\n",
    "]\n",
    "\n",
    "country_options = sorted([\n",
    "    'United States of America',\n",
    "    'Germany',\n",
    "    'United Kingdom of Great Britain and Northern Ireland',\n",
    "    'India',\n",
    "    'Canada',\n",
    "    'France',\n",
    "    'Brazil',\n",
    "    'Spain',\n",
    "    'Netherlands',\n",
    "    'Australia',\n",
    "    'Italy',\n",
    "    'Poland',\n",
    "    'Sweden',\n",
    "    'Russian Federation',\n",
    "    'Switzerland',\n",
    "    'other'\n",
    "])\n",
    "\n",
    "ai_models_options = [\n",
    "    'ChatGPT',\n",
    "    'Google Gemini',\n",
    "    'GitHub Copilot',\n",
    "    'Claude',\n",
    "    'Llama 3',\n",
    "    'Other'\n",
    "]\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# UI Title\n",
    "# --------------------------------------------------\n",
    "st.title(\"💻 DEV_INSIGHTS_PREDICTOR_v2.0\")\n",
    "st.markdown(\"Predict **Salary** and **Job Satisfaction** for developers.\")\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Layout: Three Columns\n",
    "# --------------------------------------------------\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "# Column 1\n",
    "with col1:\n",
    "    country = st.selectbox(\"🌍 Location\", country_options)\n",
    "    dev_type = st.selectbox(\"💼 Role\", dev_type_options)\n",
    "    employment = st.selectbox(\"📄 Employment Status\", employment_options)\n",
    "    org_size = st.selectbox(\"🏢 Organization Size\", org_size_options)\n",
    "    ic_pm = st.selectbox(\"👔 Management Role\", ic_pm_options)\n",
    "    remote = st.selectbox(\"🏠 Work Mode\", remote_options)\n",
    "\n",
    "# Column 2\n",
    "with col2:\n",
    "    age = st.selectbox(\"🎂 Age\", age_options)\n",
    "    ed_level = st.selectbox(\"🎓 Education\", ed_level_options)\n",
    "    work_exp = st.number_input(\"📈 Work Experience (Years)\", min_value=0, value=5)\n",
    "    years_code = st.number_input(\"💻 Years of Coding\", min_value=0, value=5)\n",
    "    learn_code = st.selectbox(\"📚 Learning Path\", learn_code_options)\n",
    "\n",
    "# Column 3\n",
    "with col3:\n",
    "    learn_ai = st.selectbox(\"🤖 AI Learning Method\", learn_code_ai_options)\n",
    "    ai_models = st.selectbox(\"🧠 Preferred AI Model\", ai_models_options)\n",
    "    ai_threat = st.selectbox(\"⚠️ AI Threat Perception\", ai_threat_options)\n",
    "    purchase = st.selectbox(\"💰 Purchase Influence\", purchase_options)\n",
    "    new_role = st.selectbox(\"🔄 Considering New Role\", new_role_options)\n",
    "    tool_work = st.number_input(\"🛠️ Work Tools Count\", min_value=0, value=1)\n",
    "    tool_pers = st.number_input(\"🏠 Personal Tools Count\", min_value=0, value=1)\n",
    "\n",
    "\n",
    "# --------------------------------------------------\n",
    "# Prediction Button\n",
    "# --------------------------------------------------\n",
    "if st.button(\"🚀 RUN PREDICTION\", use_container_width=True):\n",
    "    try:\n",
    "        salary, satisfaction = predict_job_satisfaction(\n",
    "            age,\n",
    "            ed_level,\n",
    "            employment,\n",
    "            work_exp,\n",
    "            learn_code,\n",
    "            learn_ai,\n",
    "            years_code,\n",
    "            dev_type,\n",
    "            org_size,\n",
    "            ic_pm,\n",
    "            remote,\n",
    "            purchase,\n",
    "            ai_threat,\n",
    "            new_role,\n",
    "            tool_work,\n",
    "            tool_pers,\n",
    "            country,\n",
    "            ai_models\n",
    "        )\n",
    "\n",
    "        st.success(\"Prediction completed successfully!\")\n",
    "\n",
    "        result_col1, result_col2 = st.columns(2)\n",
    "\n",
    "        with result_col1:\n",
    "            st.metric(\n",
    "                label=\"💰 Predicted Salary\",\n",
    "                value=f\"${salary:,.2f}\"\n",
    "            )\n",
    "\n",
    "        with result_col2:\n",
    "            st.metric(\n",
    "                label=\"😊 Predicted Job Satisfaction\",\n",
    "                value=str(satisfaction)\n",
    "            )\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"Prediction failed: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
