{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3331ab57-b962-4433-8314-19001e4ba9cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import gradio as gr\n",
    "import pandas as pd\n",
    "import joblib\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "\n",
    "class change_data_type(BaseEstimator,TransformerMixin):\n",
    "    def fit(self,X,y=None):\n",
    "        return self\n",
    "\n",
    "    def transform(self,X):\n",
    "        X=X.copy()\n",
    "        for col in X.columns:\n",
    "            if X[col].dtype in ['object']:\n",
    "                X[col]=X[col].astype('category')\n",
    "            else:\n",
    "                X[col]=X[col]\n",
    "        return X\n",
    "\n",
    "models = joblib.load(\"full_system.pkl\")\n",
    "\n",
    "salary_model = models[\"salary_model\"]\n",
    "satisfaction_model = models[\"satisfaction_model\"]\n",
    "\n",
    "def predict_job_satisfaction(Age, EdLevel, Employment, WorkExp, LearnCodeChoose, LearnCodeAI, YearsCode, DevType, OrgSize, ICorPM, RemoteWork, PurchaseInfluence, AIThreat, NewRole, ToolCountWork, ToolCountPersonal, Country, AIModelsChoice):\n",
    "\n",
    "    input_features_for_salary = pd.DataFrame([\n",
    "        {\n",
    "        \"Age\": Age, \"EdLevel\": EdLevel, \"Employment\": Employment, \"WorkExp\": WorkExp,\n",
    "        \"LearnCodeChoose\": LearnCodeChoose, \"LearnCodeAI\": LearnCodeAI, \"YearsCode\": YearsCode,\n",
    "        \"DevType\": DevType, \"OrgSize\": OrgSize, \"ICorPM\": ICorPM, \"RemoteWork\": RemoteWork,\n",
    "        \"PurchaseInfluence\": PurchaseInfluence, \"AIThreat\": AIThreat, \"NewRole\": NewRole,\n",
    "        \"ToolCountWork\": ToolCountWork, \"ToolCountPersonal\": ToolCountPersonal,\n",
    "        \"Country\": Country, \"AIModelsChoice\": AIModelsChoice\n",
    "    }\n",
    "    ])\n",
    "\n",
    "    # Predict salary\n",
    "    predicted_salary = salary_model.predict(input_features_for_salary)[0]\n",
    "\n",
    "    # Prepare features for satisfaction prediction\n",
    "    input_features_for_satisfaction = input_features_for_salary.copy()\n",
    "\n",
    "    input_features_for_satisfaction[\"pred_salary\"] = predicted_salary\n",
    "\n",
    "    # Predict job satisfaction\n",
    "    job_satisfaction_category = satisfaction_model.predict(input_features_for_satisfaction)[0]\n",
    "\n",
    "    return f\"Predicted Salary: ${predicted_salary:,.2f}\", f\"Predicted Job Satisfaction: {job_satisfaction_category}\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "94b9dcf3-ec37-4b87-8041-2501f62e3f43",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* Running on local URL:  http://0.0.0.0:7860\n",
      "\n",
      "Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://localhost:7860/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Closing server running on port: 7860\n",
      "\n",
      "App stopped automatically after prediction.\n",
      "Keyboard interruption in main thread... closing server.\n"
     ]
    }
   ],
   "source": [
    "import gradio as gr\n",
    "import threading\n",
    "import time\n",
    "\n",
    "custom_css = \"\"\"\n",
    ".gradio-container {background-color: #0b0f19 !important;}\n",
    ".panel {border-radius: 15px !important; border: 1px solid #1e293b !important; padding: 20px !important; background: #111827 !important;}\n",
    "footer {display: none !important;}\n",
    "#title-text {text-align: center; color: #10b981; margin-bottom: 20px;}\n",
    "#predict-btn {background: linear-gradient(90deg, #059669 0%, #10b981 100%) !important; border: none !important; color: white !important; font-weight: bold !important;}\n",
    "#predict-btn:hover {transform: scale(1.02); transition: all 0.2s ease;}\n",
    "\"\"\"\n",
    "\n",
    "theme = gr.themes.Soft(\n",
    "    primary_hue=\"emerald\",\n",
    "    secondary_hue=\"slate\",\n",
    "    neutral_hue=\"slate\",\n",
    "    font=[gr.themes.GoogleFont(\"Inter\"), \"ui-sans-serif\", \"system-ui\", \"sans-serif\"]\n",
    ").set(\n",
    "    body_background_fill=\"#0b0f19\",\n",
    "    block_background_fill=\"#111827\",\n",
    "    block_border_width=\"1px\",\n",
    "    block_label_text_color=\"#94a3b8\"\n",
    ")\n",
    "\n",
    "age_options = ['18-24 years old', '25-34 years old', '35-44 years old', '45-54 years old', '55-64 years old', '65 years or older']\n",
    "ed_level_options = ['Bachelor’s degree', 'Master’s degree', 'Some college/university study without earning a degree', 'Secondary school', 'Professional degree', 'Associate degree', 'Primary/elementary school', 'Other doctoral degree', 'Something else']\n",
    "employment_options = ['Employed, full-time', 'Independent contractor, freelancer, or self-employed', 'Employed, part-time', 'Retired', 'Not employed, but looking for work', 'Student, full-time']\n",
    "learn_code_options = ['Other online resources', 'Books / Physical media', 'Online Courses or Certification', 'On the job training', 'School (i.e., University, College, etc)', 'Friend or family member']\n",
    "learn_code_ai_options = ['Online courses', 'Chatbots', 'Other', 'Videos', 'Interactive tutorials']\n",
    "dev_type_options = ['Developer, back-end', 'Developer, front-end', 'Developer, full-stack', 'Developer, desktop or enterprise applications', 'Developer, mobile', 'Data scientist or machine learning specialist', 'Engineer, data', 'DevOps specialist']\n",
    "org_size_options = ['20 to 99 employees', '100 to 499 employees', '10,000 or more employees', '1,000 to 4,999 employees', '2 to 9 employees', '500 to 999 employees', 'Just me - I am a freelancer, sole proprietor, etc.']\n",
    "ic_pm_options = ['Individual contributor', 'Program manager']\n",
    "remote_options = ['Hybrid', 'Remote', 'In-person']\n",
    "purchase_options = ['I have some influence', 'I have little or no influence', 'I am a primary decision maker']\n",
    "ai_threat_options = ['I’m not at all concerned', 'I’m somewhat concerned', 'I’m very concerned']\n",
    "new_role_options = ['Not sure', 'Yes', 'No']\n",
    "country_options = sorted(['United States of America', 'Germany', 'United Kingdom of Great Britain and Northern Ireland', 'India', 'Canada', 'France', 'Brazil', 'Spain', 'Netherlands', 'Australia', 'Italy', 'Poland', 'Sweden', 'Russian Federation', 'Switzerland', 'other'])\n",
    "ai_models_options = ['ChatGPT', 'Google Gemini', 'GitHub Copilot', 'Claude', 'Llama 3', 'Other']\n",
    "\n",
    "def run_and_stop(*args):\n",
    "    salary, satisfaction = predict_job_satisfaction(*args)\n",
    "    def delayed_close():\n",
    "        time.sleep(5)\n",
    "        ui.close()\n",
    "        print(\"\\nApp stopped automatically after prediction.\")\n",
    "    threading.Thread(target=delayed_close).start()\n",
    "    return salary, satisfaction\n",
    "\n",
    "with gr.Blocks(theme=theme, css=custom_css, title=\"DevInsights Pro\") as ui:\n",
    "    gr.Markdown(\"# 🚀 DEV_INSIGHTS_PREDICTOR v2.0\", elem_id=\"title-text\")\n",
    "    gr.Markdown(\"### *Empowering Developers with Data-Driven Career Insights*\", elem_id=\"title-text\")\n",
    "\n",
    "    with gr.Tabs():\n",
    "        with gr.TabItem(\"👤 Professional Profile\"):\n",
    "            with gr.Row():\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    country = gr.Dropdown(country_options, label=\"🌍 Location\", info=\"Where are you based?\")\n",
    "                    dev_type = gr.Dropdown(dev_type_options, label=\"💻 Current Role\", info=\"Select your primary role\")\n",
    "                    employment = gr.Dropdown(employment_options, label=\"💼 Employment Status\")\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    org_size = gr.Dropdown(org_size_options, label=\"🏢 Organization Size\")\n",
    "                    ic_pm = gr.Radio(ic_pm_options, label=\"👔 Career Track\", value=\"Individual contributor\")\n",
    "                    remote = gr.Radio(remote_options, label=\"🏠 Work Style\", value=\"Hybrid\")\n",
    "\n",
    "        with gr.TabItem(\"🎓 Education & Experience\"):\n",
    "            with gr.Row():\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    age = gr.Dropdown(age_options, label=\"📅 Age Group\")\n",
    "                    ed_level = gr.Dropdown(ed_level_options, label=\"🎓 Education Level\")\n",
    "                    learn_code = gr.Dropdown(learn_code_options, label=\"📚 Learning Path\")\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    work_exp = gr.Slider(0, 50, step=1, label=\"⏳ Total Work Experience (Years)\", value=5)\n",
    "                    years_code = gr.Slider(0, 50, step=1, label=\"⌨️ Coding Experience (Years)\", value=5)\n",
    "\n",
    "        with gr.TabItem(\"🤖 AI & Technology\"):\n",
    "            with gr.Row():\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    learn_ai = gr.Dropdown(learn_code_ai_options, label=\"✨ How you learn AI\")\n",
    "                    ai_models = gr.Dropdown(ai_models_options, label=\"🛠️ Favorite AI Tool\")\n",
    "                    ai_threat = gr.Dropdown(ai_threat_options, label=\"⚠️ Perception of AI Threat\")\n",
    "                with gr.Column(variant=\"panel\"):\n",
    "                    purchase = gr.Dropdown(purchase_options, label=\"🛒 Software Purchase Influence\")\n",
    "                    new_role = gr.Radio(new_role_options, label=\"🔍 Looking for a new role?\", value=\"Not sure\")\n",
    "                    with gr.Row():\n",
    "                        tool_work = gr.Number(label=\"🛠️ Tools (Work)\", value=1)\n",
    "                        tool_pers = gr.Number(label=\"🛠️ Tools (Personal)\", value=1)\n",
    "\n",
    "    submit_btn = gr.Button(\"⚡ ANALYZE MY CAREER\", variant=\"primary\", elem_id=\"predict-btn\")\n",
    "\n",
    "    with gr.Row(variant=\"compact\"):\n",
    "        out_salary = gr.Textbox(label=\"💰 Estimated Annual Salary\", placeholder=\"Awaiting analysis...\")\n",
    "        out_satisfaction = gr.Textbox(label=\"🌟 Predicted Job Satisfaction\", placeholder=\"Awaiting analysis...\")\n",
    "\n",
    "    submit_btn.click(\n",
    "        fn=run_and_stop,\n",
    "        inputs=[age, ed_level, employment, work_exp, learn_code, learn_ai, years_code, dev_type, org_size, ic_pm, remote, purchase, ai_threat, new_role, tool_work, tool_pers, country, ai_models],\n",
    "        outputs=[out_salary, out_satisfaction]\n",
    "    )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    ui.launch(server_name=\"0.0.0.0\", server_port=7860, share=True, debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
